/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */
import java.security.MessageDigest

group = "io.github.skoogjacob"

version = "0.2.0"

description = "test library, testing a FOSS license combo"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    // publish to maven
    `maven-publish`
    signing
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile
    // classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain { languageVersion = JavaLanguageVersion.of(17) }
    withSourcesJar()
    withJavadocJar()
}

publishing {
    publications {
        create<MavenPublication>("mavenJava") {
            artifactId = "license-test"
            from(components["java"])

            pom {
                name.set("io.github.skoogjacob:license-test")
                description.set(project.description)
                url.set("https://skoogjacob.github.io/")

                // ─────────────── LICENSES ───────────────
                licenses {
                    license {
                        name.set("QPL-1.0")
                        url.set("https://opensource.org/license/qpl-1-0")
                    }
                    license {
                        name.set("Frameworx-1.0")
                        url.set("https://opensource.org/license/frameworx-php")
                    }
                    license {
                        name.set("MirOS")
                        url.set("https://opensource.org/license/miros-html")
                    }
                    license {
                        name.set("OFL-1.1")
                        url.set("https://opensource.org/license/ofl-1-1")
                    }
                }

                // ─────────────── DEVELOPER ───────────────
                developers {
                    developer {
                        name.set("Jacob Skoog")
                        email.set("jacob.skoog@pm.me")
                        organization.set("skoogjacob")
                        organizationUrl.set("https://skoogjacob.github.io/")
                    }
                }

                // ─────────────── SCM ───────────────
                scm {
                    connection.set("scm:git:https://github.com/SkoogJacob/gradle-license-test.git")
                    developerConnection.set("scm:git:https://github.com/SkoogJacob/gradle-license-test.git")
                    url.set("https://github.com/SkoogJacob/gradle-license-test")
                }
            }
        }
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

signing {
    val keyId = findProperty("signing.keyId") as String?
    val keyPassword = findProperty("signing.password") as String?
    val keyFilePath = findProperty("signing.secretKeyFile") as String?
    val keyFile = keyFilePath?.let { File(it) }
    if (keyFile != null && keyFile.exists()) {
        val keyText = keyFile.readText(Charsets.UTF_8)
        useInMemoryPgpKeys(keyId, keyText, keyPassword)
        logger.lifecycle("Using in-memory PGP key from $keyFilePath")
    } else {
        logger.warn("No signing key found at $keyFilePath, using system gpg as fallback")
        useGpgCmd()
    }
    sign(publishing.publications["mavenJava"])
}

tasks.register("generateChecksums") {
    val publicationDir = layout.buildDirectory.dir("publications/mavenJava")
    outputs.dir(publicationDir)
    doLast {
        val pubDir = publicationDir.get().asFile
        pubDir.walkTopDown()
                .filter {
                    it.isFile &&
                            !it.name.endsWith(".asc") &&
                            !it.name.endsWith(".sha1") &&
                            !it.name.endsWith(".md5")
                }
                .forEach { file ->
                    val bytes = file.readBytes()
                    fun digest(algorithm: String): String {
                        val md = MessageDigest.getInstance(algorithm)
                        val hash = md.digest(bytes)
                        return hash.joinToString("") { b -> "%02x".format(b) }
                    }
                    file.resolveSibling("${file.name}.sha1").writeText(digest("SHA-1"))
                    file.resolveSibling("${file.name}.md5").writeText(digest("MD5"))
                }
    }
}

tasks.named("publishToMavenLocal") { finalizedBy("generateChecksums") }
