/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.1.0/userguide/building_java_projects.html in the Gradle documentation.
 */
group = "io.github.skoogjacob"
version = "0.1.0"
description = "test library, testing a FOSS license combo"

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    alias(libs.plugins.kotlin.jvm)

    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    // publish to maven
    `maven-publish`
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use the Kotlin Test integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the JUnit 5 integration.
    testImplementation(libs.junit.jupiter.engine)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile
    // classpath.
    implementation(libs.guava)
}

// Apply a specific Java toolchain to ease working on different environments.
java { toolchain { languageVersion = JavaLanguageVersion.of(21) } }

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}
publishing {
    publications {
        create<MavenPublication>("mavenKotlin") {
            from(components["java"])
            pom {
                name = "License test library"
                description = "this package is meant to test license combos"
                licenses {
                    license {
                        name = "GPL-3.0-only"
                        url = "https://opensource.org/licenses/gpl-3-0"
                        distribution = "repo"
                    }
                    license {
                        name = "NTP"
                        url = "https://opensource.org/license/ntp-license-php"
                        distribution = "repo"
                    }
                }
                developers {
                    developer {
                        name = "Jacob Skoog"
                        email = "jacob.skoog@pm.me"
                        organization = "github.io"
                        organizationUrl = "https://skoogjacob.github.io/"
                    }
                }
                scm {

                }
            }
        }
    }
}
