/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Library {
    fun someLibraryMethod(): Boolean {
        return true
    }

    fun addNums(a: Int, b: Int): Int {
        return a + b
    }
}
